on: push
name: New workflow
jobs:
  dockerLogin:
    name: Docker Login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Login
      uses: azure/docker-login@v1
      env:
        password: ${{ secrets.DOCKER_PASSWORD }}
        username: ${{ secrets.DOCKER_USERNAME }}
    - run: |
           docker build . -t patrickoyarzun/concourse-prof:${{ github.sha }}
           docker push patrickoyarzun/concourse-prof:${{ github.sha }}
